### ISSUE TITLE
Please make this part of the standard blender distribution as an optional addon

### ISSUE THREAD

**Issue by lpadukana** [zeffii/Blender_CAD_utils#26]
I feel this should be part of the standard distribution so the tools are readily available. As a first step, maybe get this included in the bundle?

**Comment by zeffii** [comment]
That's not a decision that is up to me. (including in standard distribution)
But the add-on is available in as part of what is called 'addons_contrib', user contributed add-ons distributed in daily builds at [builder.blender.org](https://builder.blender.org/download/) -- the version I uploaded there is not as cutting edge as this one. (I should update that because I've added bug fixes)

**Comment by zeffii** [comment]
mesh_tiny_cad has now been committed to Trunk (Release) and if everything goes OK will be included in the 2.78 release.
